#!/usr/bin/env bash
# One-time local setup for development on this machine (no Docker needed).
# - Creates PlantOps database logins + the `plantops` and `plantops_test` databases on the local Postgres
#   (asks for your sudo password, because only the postgres superuser can create logins).
# - Writes .env with freshly generated dev passwords and an SSO signing key. .env is never committed.
set -euo pipefail
cd "$(dirname "$0")/.."

if [ -f .env ]; then
  echo ".env already exists - not overwriting. Delete it first if you really want to regenerate everything."
  exit 1
fi

gen() { openssl rand -hex 16; }
OWNER_PW=$(gen); APP_PW=$(gen); SUPER_PW=$(gen); SUPER_ADMIN_PW=$(gen)

sudo -u postgres psql -v ON_ERROR_STOP=1 \
  -v owner_pw="$OWNER_PW" -v app_pw="$APP_PW" -v super_pw="$SUPER_PW" \
  -f scripts/setup-local-db.sql

SSO_KEY=$(node scripts/generate-sso-key.mjs)

url() { echo "postgres://$1:$2@localhost:5432/$3"; }
cat > .env <<ENV
# Local development settings - generated by scripts/setup-local-db.sh. Never commit this file.
DATABASE_URL_OWNER=$(url plantops_owner "$OWNER_PW" plantops)
DATABASE_URL_APP=$(url platform_app "$APP_PW" plantops)
DATABASE_URL_SUPER=$(url platform_super "$SUPER_PW" plantops)
TEST_DATABASE_URL_OWNER=$(url plantops_owner "$OWNER_PW" plantops_test)
TEST_DATABASE_URL_APP=$(url platform_app "$APP_PW" plantops_test)
TEST_DATABASE_URL_SUPER=$(url platform_super "$SUPER_PW" plantops_test)
PLATFORM_URL=http://localhost:3000
SSO_PRIVATE_JWK_B64=$SSO_KEY
SUPER_ADMIN_EMAIL=admin@plantops.local
SUPER_ADMIN_PASSWORD=$SUPER_ADMIN_PW
ENV

echo
echo "Done. Wrote .env"
echo "First super_admin login (after 'pnpm db:migrate && pnpm db:seed'):"
echo "  email:    admin@plantops.local"
echo "  password: $SUPER_ADMIN_PW   (also stored in .env)"
